os: linux

language: go

go: "1.14"

notifications:
  email: false

services:
  - docker

env:
  GO111MODULE=on

script:
  - sudo chmod +x test.sh
  - sudo docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
