FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/roman-mazur/bood/cmd/bood

WORKDIR /go/src/practice-3
COPY . .

#ENTRYPOINT ["bood_rebase", "integration-tests"]
ENTRYPOINT ["bood", "integration-tests"]
